version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=rahel81
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=rahel81

    ports:
      - '5432:5432'